const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let csrf='',items=[],sites=[],current=null;
async function api(path,options={}){const r=await fetch(path,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,...options.headers}});const d=await r.json();if(!r.ok)throw new Error(d.error||d.message||'操作失敗');return d}
const field=(name,label,value='',type='text')=>`<label>${label}<input name="${name}" value="${esc(value)}" type="${type}"></label>`;
const select=(name,label,options,value)=>`<label>${label}<select name="${name}">${options.map(([v,l])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;
function renderEditor(item){
 current=item;const kind=$('#kind').value,d=item?.data||{};$('#editor').hidden=false;
 const common=field('title','標題／名稱',d.title)+`<label>摘要<textarea name="summary" rows="4">${esc(d.summary)}</textarea></label>`+field('sort_order','排序',d.sort_order??0,'number');
 let fields='';if(kind==='settings')fields=field('article_limit','首頁最新消息顯示筆數（1–50）',d.article_limit??7,'number');
 if(kind==='article')fields=field('external_url','文章外部網址',d.external_url,'url')+field('image_url','縮圖網址',d.image_url,'url')+field('date','發布日期',d.date,'date');
 if(kind==='activity')fields=field('start_at','開始時間',d.start_at?new Date(d.start_at).toLocaleString('sv-SE',{timeZone:'Asia/Taipei'}).replace(' ','T').slice(0,16):'','datetime-local')+field('end_at','結束時間',d.end_at?new Date(d.end_at).toLocaleString('sv-SE',{timeZone:'Asia/Taipei'}).replace(' ','T').slice(0,16):'','datetime-local')+field('location','地點',d.location)+select('recruitment_type','招募類型',[['public','公開招募'],['internal','內部活動']],d.recruitment_type)+select('status','活動狀態',[['scheduled','預定'],['open','報名中'],['closed','已截止'],['cancelled','已取消'],['completed','已完成']],d.status)+field('registration_url','報名網址',d.registration_url,'url');
 if(['profile','annotation','chart'].includes(kind))fields+=select('site_id','樣點（共用圖表可留空）',[['','請選擇'],...sites.map(s=>[String(s.id),s.name_zh])],String(item?.site_id||''));
 if(kind==='profile')fields+=field('report_url','最新報告網址',d.report_url,'url')+field('image_url','圖片網址',d.image_url,'url')+field('date','報告日期',d.date,'date');
 if(kind==='annotation')fields+=field('date','事件日期',d.date,'date')+field('source_url','查證來源網址',d.source_url,'url');
 if(kind==='chart')fields+=select('chart','資料類型',[['live_coral','活珊瑚覆蓋率'],['substrate','底質'],['taxa','物種'],['impact','環境衝擊'],['bleaching','底質白化']],d.chart)+select('is_visible','公開顯示',[['true','顯示'],['false','隱藏']],String(d.is_visible??true))+field('year_from','起始年份',d.year_from??'','number')+field('year_to','結束年份',d.year_to??'','number')+field('depths_m','深度（逗號分隔）',(d.depths_m||[]).join(','))+field('category_keys','顯示項目代碼／物種編號（逗號分隔，空白為全部）',(d.category_keys||[]).join(','))+`<fieldset><legend>共用圖表樣點</legend>${sites.map(s=>`<label><input name="site_ids" type="checkbox" value="${s.id}" ${(d.site_ids||[]).includes(s.id)?'checked':''}>${esc(s.name_zh)}</label>`).join('')}</fieldset>`;
 if(kind==='development')fields+=field('county','縣市',d.county)+field('authority','主管機關',d.authority)+field('area_m2','面積 m²（未知留空）',d.area_m2??'','number')+field('investment_ntd','投資金額 NTD（未知留空）',d.investment_ntd??'','number')+field('status','正式程序狀態（人工查證）',d.status)+field('source_url','資料來源網址',d.source_url,'url')+`<label>點／面邊界（GeoJSON Geometry，保留完整座標）<textarea name="geometry" rows="5">${esc(JSON.stringify(d.geometry||{type:'Point',coordinates:[]},null,2))}</textarea></label><h3>事件時間軸</h3><div id="timeline">${(d.timeline||[]).map(timelineRow).join('')}</div><button type="button" id="add-timeline">新增時間軸事件</button><h3>圖片及授權</h3><div id="media">${(d.media||[]).map(mediaRow).join('')}</div><button type="button" id="add-media">新增圖片</button>`;
 $('#editor').innerHTML=`<h2>${item?'編輯內容 #'+item.id:'新增草稿'}</h2><form id="edit-form"><div class="filters">${common}${fields}${select('publication_status','發布狀態',[['draft','草稿'],['published','已發布'],['archived','封存']],item?.publication_status||'draft')}</div><button>儲存</button> <button type="button" id="cancel">取消</button></form>`;
 $('#cancel').onclick=()=>$('#editor').hidden=true;if($('#add-timeline'))$('#add-timeline').onclick=()=>$('#timeline').insertAdjacentHTML('beforeend',timelineRow({}));if($('#add-media'))$('#add-media').onclick=()=>$('#media').insertAdjacentHTML('beforeend',mediaRow({}));$('#edit-form').onsubmit=save;
}
function timelineRow(t){return `<fieldset class="timeline-row"><legend>時間軸事件</legend>${field('t_title','標題',t.title)}${field('t_date','日期（依精度：YYYY／YYYY-MM／YYYY-MM-DD）',t.date)}${select('t_precision','日期精度',[['day','日'],['month','月'],['year','年'],['unknown','未知']],t.date_precision)}${field('t_description','說明',t.description)}${field('t_status','狀態',t.status)}${field('t_source','查證來源',t.source_url,'url')}${field('t_sort','未知日期排序',t.sort_order??0,'number')}${select('t_published','發布此事件',[['false','草稿'],['true','發布']],String(t.is_published||false))}<button type="button" onclick="this.parentElement.remove()">移除此事件</button></fieldset>`}
function mediaRow(m){return `<fieldset class="media-row"><legend>圖片</legend>${field('m_url','圖片網址',m.url,'url')}${field('m_alt','替代文字',m.alt)}${select('m_valid','圖片有效性',[['false','尚未確認'],['true','已確認有效']],String(m.is_valid||false))}${select('m_licensed','授權',[['false','尚未確認'],['true','已確認授權']],String(m.license_confirmed||false))}${select('m_published','發布圖片',[['false','草稿'],['true','發布']],String(m.is_published||false))}<button type="button" onclick="this.parentElement.remove()">移除此圖片</button></fieldset>`}
async function save(e){e.preventDefault();const form=e.target,f=new FormData(form),kind=$('#kind').value,d={};const status=f.get('publication_status');if(status==='archived'&&!confirm('確定封存此內容？封存後不再出現在公開網站。'))return;
 for(const [k,v] of f){if(['site_id','site_ids','publication_status','geometry'].includes(k)||k.startsWith('t_')||k.startsWith('m_'))continue;if(['area_m2','investment_ntd','year_from','year_to','article_limit'].includes(k)){if(v!=='')d[k]=Number(v)}else if(k==='sort_order')d[k]=Number(v);else if(k==='is_visible')d[k]=v==='true';else if(k==='depths_m')d[k]=v?String(v).split(',').map(Number):[];else if(k==='category_keys')d[k]=v?String(v).split(',').map(s=>s.trim()):[];else if(k==='start_at'||k==='end_at')d[k]=v+':00+08:00';else d[k]=v}
 try{if(kind==='development'){d.geometry=JSON.parse(f.get('geometry'));d.timeline=[...form.querySelectorAll('.timeline-row')].map(el=>{const v=n=>el.querySelector(`[name=${n}]`).value;return {title:v('t_title'),date:v('t_date'),date_precision:v('t_precision'),description:v('t_description'),status:v('t_status'),source_url:v('t_source'),sort_order:Number(v('t_sort')),is_published:v('t_published')==='true'}});d.media=[...form.querySelectorAll('.media-row')].map(el=>{const v=n=>el.querySelector(`[name=${n}]`).value;return {url:v('m_url'),alt:v('m_alt'),is_valid:v('m_valid')==='true',license_confirmed:v('m_licensed')==='true',is_published:v('m_published')==='true'}})}if(kind==='chart')d.site_ids=f.getAll('site_ids').map(Number);
 const body={kind,data:d,site_id:f.get('site_id')?Number(f.get('site_id')):null,publication_status:status,version:current?.updated_at||'',confirm:status==='archived'};const saved=await api(`/api/admin/public-content/${kind}${current?'/'+current.id:''}`,{method:current?'PATCH':'POST',body:JSON.stringify(body)});$('#message').textContent=current?'已儲存。':'已建立草稿；核對後可改為已發布。';await load();renderEditor(saved)
 }catch(err){$('#message').textContent=err.message}
}
async function load(){try{const kind=$('#kind').value;$('#editor').hidden=true;$('#new').hidden=kind==='event'||kind==='audit';items=await api(kind==='audit'?'/api/admin/public-audit':kind==='event'?'/api/admin/reef-check-data/events':'/api/admin/public-content/'+kind);$('#list').innerHTML=items.map(c=>kind==='audit'?`<section class="card"><h3>${esc(c.kind)} #${c.id}</h3><p>${esc(c.created_at)}</p><pre style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(JSON.stringify(c.details,null,2))}</pre></section>`:kind==='event'?`<div class="card"><h3>${esc(c.site_name)} · ${esc(c.survey_date)} ${esc(c.event_time)} · ${c.depth_m}m</h3><p>${esc(c.event_id)}</p><p>目前狀態：${esc(c.publication_status)}</p><select id="status-${c.id}"><option value="draft">草稿</option><option value="published">已發布</option><option value="archived">封存</option></select><button data-publish="${c.id}">更新發布狀態</button><details><summary>查看原始資料與記錄者</summary><div id="detail-${c.id}"></div><button data-review="${c.id}">載入核對資料</button></details></div>`:`<div class="card pair"><div><b>${esc(c.data.title)}</b><p>${esc(c.publication_status)} · ${esc(c.updated_at)}</p></div><button data-edit="${c.id}">編輯</button></div>`).join('')||'<p>尚無資料。</p>';for(const c of items){if(kind==='event')$('#status-'+c.id).value=c.publication_status||'draft'}}catch(e){$('#message').textContent=e.message}}
$('#list').onclick=async e=>{const edit=e.target.closest('[data-edit]');if(edit)renderEditor(items.find(c=>c.id===Number(edit.dataset.edit)));const publish=e.target.closest('[data-publish]');if(publish){const id=Number(publish.dataset.publish),status=$('#status-'+id).value;if(!confirm(`確定將調查 #${id} 改為${status==='published'?'已發布':status==='archived'?'封存':'草稿'}？請先核對原始資料。`))return;try{await api(`/api/admin/reef-check-data/events/${id}/publication`,{method:'PATCH',body:JSON.stringify({publication_status:status,confirm:true})});await load()}catch(e){$('#message').textContent=e.message}}const review=e.target.closest('[data-review]');if(review){try{const d=await api('/api/admin/reef-check-data/events/'+review.dataset.review);const el=$('#detail-'+review.dataset.review);el.textContent=JSON.stringify(d,null,2);el.style.whiteSpace='pre-wrap'}catch(e){$('#message').textContent=e.message}}};
$('#kind').onchange=load;$('#new').onclick=()=>renderEditor(null);
try{const session=await api('/api/session');if(!session.authenticated||session.user?.role!=='admin'){$('#message').innerHTML='權限不足，請先<a href="/admin/">登入管理後台</a>。'}else{csrf=session.csrfToken;sites=await api('/api/admin/sites');$('#workspace').hidden=false;await load()}}catch(e){$('#message').textContent=e.message}
